allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  vue-demi: true
  yarn: true
patchedDependencies:
  '@capacitor-community/admob@8.0.0': patches/@capacitor-community__admob@8.0.0.patch
